# =============================================================================
# 12_session2_random_forest.py
# Stage: Session 2
# Description: Random Forest tuning across 3 configurations on NASA MDP data.
#              All three configurations fail the overfit gate.
#
# NEGATIVE FINDING: Random Forest consistently overfits on SMOTE-augmented
# NASA MDP data across all depth configurations. This is attributed to the
# interaction between bagged tree ensembles and synthetic minority samples
# generated by SMOTE — a known limitation in imbalanced learning literature.
#
# RESULTS:
#   RF v1 (depth=7):  Val F1: 0.6492 | Gap: 0.1402 ❌
#   RF v2 (depth=5):  Val F1: 0.6395 | Gap: 0.0964 ❌
#   RF v3 (depth=6):  Val F1: 0.6390 | Gap: 0.1273 ❌
# =============================================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, f1_score

OVERFIT_THRESHOLD = 0.05
TARGET_NAMES = ['Clean', 'Defective']

def evaluate_rf(model, X_train, y_train, X_val, y_val, name):
    model.fit(X_train, y_train)
    train_preds = model.predict(X_train)
    val_preds = model.predict(X_val)

    train_f1 = f1_score(y_train, train_preds, average='macro')
    val_f1 = f1_score(y_val, val_preds, average='macro')
    gap = train_f1 - val_f1
    status = "✅ PASS" if gap <= OVERFIT_THRESHOLD else "❌ OVERFIT"

    print(f"\n--- {name} ---")
    print(f"Training F1:   {train_f1:.4f}")
    print(f"Validation F1: {val_f1:.4f}")
    print(f"Overfit Gap:   {gap:.4f}  {status}")
    print(classification_report(y_val, val_preds, target_names=TARGET_NAMES))

    return val_f1, gap

def run_random_forest_session2(X_train, y_train, X_val, y_val):
    print("=" * 55)
    print("SESSION 2 — Random Forest Tuning (NASA MDP)")
    print("=" * 55)
    results = {}

    # RF v1 — initial configuration
    rf1 = RandomForestClassifier(n_estimators=100, max_depth=7, min_samples_leaf=10,
                                  max_features='sqrt', random_state=42,
                                  class_weight='balanced', n_jobs=-1)
    results['RF v1 (depth=7)'] = evaluate_rf(rf1, X_train, y_train, X_val, y_val,
                                               "Random Forest v1 (depth=7, leaf=10)")

    # RF v2 — increased regularization
    rf2 = RandomForestClassifier(n_estimators=100, max_depth=5, min_samples_leaf=20,
                                  max_features='sqrt', random_state=42,
                                  class_weight='balanced', n_jobs=-1)
    results['RF v2 (depth=5)'] = evaluate_rf(rf2, X_train, y_train, X_val, y_val,
                                               "Random Forest v2 (depth=5, leaf=20)")

    # RF v3 — fine tuned
    rf3 = RandomForestClassifier(n_estimators=100, max_depth=6, min_samples_leaf=15,
                                  max_features='sqrt', min_samples_split=10,
                                  random_state=42, class_weight='balanced', n_jobs=-1)
    results['RF v3 (depth=6)'] = evaluate_rf(rf3, X_train, y_train, X_val, y_val,
                                               "Random Forest v3 (depth=6, leaf=15, split=10)")

    # Summary
    print("\n" + "=" * 55)
    print("RANDOM FOREST TUNING SUMMARY — NEGATIVE FINDING")
    print("=" * 55)
    print(f"{'Config':<20} {'Val F1':>8} {'Gap':>8} {'Status':>12}")
    print("-" * 55)
    for name, (val_f1, gap) in results.items():
        status = "✅ PASS" if gap <= OVERFIT_THRESHOLD else "❌ OVERFIT"
        print(f"{name:<20} {val_f1:>8.4f} {gap:>8.4f} {status:>12}")

    print("\nNEGATIVE FINDING: Random Forest overfits across all 3 configurations.")
    print("Root cause: Interaction between bagged ensembles and SMOTE synthetic samples.")
    print("Gap narrows with aggressive constraints but Val F1 drops below Logistic Regression.")
    print("Decision: Abandon Random Forest. Proceed to XGBoost.")

if __name__ == "__main__":
    print("Run this module via master_training_script.py for full pipeline execution.")
